services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: sheba-point-server
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"
    restart: unless-stopped
